# Configuration Netlify pour Biogy

# Paramètres de build
[build]
  publish = "build"
  command = "npm run build"

# Redirections pour le SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirections pour l'API (proxy CORS)
[[redirects]]
  from = "/api/*"
  to = "https://biogy-api.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"}

# Gestion des requêtes OPTIONS (CORS preflight)
[[redirects]]
  from = "/api/*"
  to = "https://biogy-api.onrender.com/api/:splat"
  status = 200
  force = true
  conditions = {method = "OPTIONS"}
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"}

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://biogy-api.onrender.com https://corsproxy.io https://api.allorigins.win https://cors-anywhere.herokuapp.com https://res.cloudinary.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://res.cloudinary.com; script-src 'self' 'unsafe-inline' 'unsafe-eval';"
