[build]
  # This tells Netlify where your project is located
  base = "/"
  # This tells Netlify what command to run
  command = "cd frontend && npm ci --legacy-peer-deps && npm run build && cd ../netlify/functions && npm install"
  # This tells Netlify where the build output is located
  publish = "frontend/build"
  # This tells Netlify where to find functions
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"
  PYTHON_VERSION = "3.9"
  NODE_OPTIONS = "--max-old-space-size=4096"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  REACT_APP_API_URL = "/.netlify/functions/proxy"

# Redirect API requests to Netlify Function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true

# Handle OPTIONS preflight requests for Netlify Function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true
  method = "OPTIONS"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200