[build]
  # This tells Netlify where your project is located
  base = "/"
  # This tells Netlify what command to run
  command = "cd frontend && npm ci --legacy-peer-deps && npm run build"
  # This tells Netlify where the build output is located
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"
  PYTHON_VERSION = "3.9"
  NODE_OPTIONS = "--max-old-space-size=4096"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  REACT_APP_API_URL = "https://biogy-api.onrender.com"

# API redirects are handled by _redirects file in public folder

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200