[build]
  base = "/"
  command = "cd frontend && npm ci && CI=false npm run build && cd ../netlify && npm install"
  publish = "frontend/build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Configuration des fonctions Netlify
[functions]
  node_bundler = "esbuild"

# Redirections pour l'API (proxy CORS)
[[redirects]]
  from = "/api/*"
  to = "https://biogy-api.onrender.com/api/:splat"
  status = 200

# Gestion des requêtes OPTIONS (CORS preflight)
[[redirects]]
  from = "/api/*"
  to = "https://biogy-api.onrender.com/api/:splat"
  status = 200
  conditions = {method = "OPTIONS"}

# Redirections pour le SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200