[build]
  base = "/"
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = "frontend/build"
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"
  PYTHON_VERSION = "3.9"
  NODE_OPTIONS = "--max-old-space-size=4096"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/api/*"
  to = "https://biogy-api.onrender.com/api/:splat"
  status = 200
  force = true

  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 