[build]
  base = "."
  command = "cd frontend && npm run build"
  publish = "frontend/build"
  functions = "frontend/netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 