[build]
  base = "/"
  command = "cd frontend && npm ci && CI=false npm run build"
  publish = "frontend/build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Redirections spécifiques pour les profils (priorité plus élevée)
[[redirects]]
  from = "/api/social/profile*"
  to = "https://biogy-api.onrender.com/api/social/profile:splat"
  status = 200
  force = true

  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"

# Redirections pour l'API (proxy CORS)
[[redirects]]
  from = "/api/*"
  to = "https://biogy-api.onrender.com/api/:splat"
  status = 200
  force = true

  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"

# Gestion des requêtes OPTIONS (CORS preflight)
[[redirects]]
  from = "/api/*"
  to = "https://biogy-api.onrender.com/api/:splat"
  status = 200
  force = true

  [redirects.conditions]
    method = "OPTIONS"

  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"

# Pas besoin de redirection pour les fonctions Netlify car elles sont gérées automatiquement

# Redirections pour le SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200