[build]
  base = "/"
  command = "npm run build"
  publish = "frontend/build"
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "https://biogy-api.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 