[build]
  base = "/"
  command = "cd frontend && npm install --force && npm list && CI=false npm run build"
  publish = "frontend/build"
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 