[build]
  base = "/"
  command = "cd frontend && npm ci && CI=false npm run build"
  publish = "frontend/build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# API redirects - these must come before the SPA redirect
[[redirects]]
  from = "/api/*"
  to = "https://biogy-api.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH", Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept, Origin"}

# Handle OPTIONS preflight requests for the API
[[redirects]]
  from = "/api/*"
  to = "https://biogy-api.onrender.com/api/:splat"
  status = 204
  force = true
  methods = ["OPTIONS"]
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH", Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept, Origin"}

# Netlify Functions redirects
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# SPA fallback - this must be the last redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200