[build]
  base = "frontend"
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = "build"
  functions = "../netlify/functions"
  
[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"
  PYTHON_VERSION = "3.9"
  NODE_OPTIONS = "--max-old-space-size=4096"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/api/*"
  to = "https://biogy-api.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 