services:
  - type: web
    name: biogy-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: yarn install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://biogy.netlify.app
    autoDeploy: true
