services:
  - type: web
    name: biogy-api
    env: node
    runtime: node
    nodeVersion: 18.x
    buildCommand: npm install express@4.18.2 && npm install
    startCommand: node --version && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://biogy.netlify.app
      - key: CORS_ENABLED
        value: "true"
    healthCheckPath: /api/health
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization, X-Requested-With, Accept, Origin"
