services:
  - type: web
    name: biogy-api
    env: node
    runtime: node
    nodeVersion: 18.x
    buildCommand: npm install
    startCommand: node --version && (node server.js || node server-fallback.js)
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://biogy.netlify.app
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization, X-Requested-With, Accept, Origin"
